name: trigger on issue
on:
  issues:
    types:
      - opened
      - created
      - labeled
  issue_comment:
    types: [created, deleted]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        run: echo "${{ toJSON(github) }}"
