name: trigger on issue
on:
  issues:
    types:
      - opened
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name : display info on any open issues
        run: echo "${{ toJSON(github) }}"
